

services:
  - type: web
    name: advanced-qna-rag
    env: python
    plan: free
    buildCommand: |-
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false