services:
  - type: web
    name: advanced-qna-rag
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false